### ISSUE TITLE
No Umlauts and Images

### ISSUE THREAD

**Issue by vfib** [spiritix/php-chrome-html2pdf#14] opened 2019-10-21 01:51 UTC
Hello,
when trying to create a Pdf from http://google.com there are no Images and Umlauts shown. Iam from Germany. This is how it looks.
[test.pdf](https://github.com/spiritix/php-chrome-html2pdf/files/3748767/test.pdf)

Is there a way to fix this, and how?

**Comment by spiritix** [comment] 2019-11-11 14:15
I didn't have any issues so far with my projects. Maybe it's something related to the Google website. Did you experience similar issues with your own websites?

**Comment by VitaliyMinenko** [comment] 2020-01-22 12:28
Have the same problem with my own projects, didnt load any images css and js, only html code.
Any ideas?

**Comment by vfib** [comment] 2020-01-22 22:01
Couldn't fix it so I'm using browsershot with headless chromium now. Needs node.

Regards

**Comment by spiritix** [comment] 2020-01-23 10:21
@VitaliyMinenko @vfib Are you guys using the library inside a VM (Vagrant, etc.)? If so, the problem is that the library tries to load the assets from **inside** the VM. E.g. it performs a request to an URL like this:

`http://myhost.local/assets/styles.css`

Which is obviously not reachable since your VM cannot resolve `myhost.local`, in contrast to your browser which performs the request from your host machine.

**Comment by spiritix** [comment] 2020-05-19 12:29
Closing this, please re-open if issue persist

**Closed by spiritix** 2020-05-19 12:29 UTC
